export type AuthUser={id:string;email?:string;user_metadata?:Record<string,unknown>};export type AuthSession={access_token:string;refresh_token:string;expires_in?:number;expires_at?:number;token_type?:string;user?:AuthUser};export type SavedRig={id:string;name:string;product_ids:number[];created_at:string;updated_at:string};export type Profile={id:string;plan:string;created_at:string;updated_at:string};
const SESSION_KEY="signalchaindb:supabase-session";const baseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,"");const anonKey=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;export const supabaseConfigured=Boolean(baseUrl&&anonKey);
function requireConfig(){if(!baseUrl||!anonKey)throw new Error("Accounts are not configured yet.");return {baseUrl,anonKey}}export function getStoredSession():AuthSession|null{if(typeof window==="undefined")return null;try{return JSON.parse(localStorage.getItem(SESSION_KEY)||"null")}catch{return null}}export function saveSession(session:AuthSession){if(typeof window==="undefined")return;const expiresAt=session.expires_at??(session.expires_in?Math.floor(Date.now()/1000)+session.expires_in:undefined);localStorage.setItem(SESSION_KEY,JSON.stringify({...session,expires_at:expiresAt}))}export function clearSession(){if(typeof window!=="undefined")localStorage.removeItem(SESSION_KEY)}
async function authFetch(path:string,init:RequestInit={},token?:string){const config=requireConfig();return fetch(`${config.baseUrl}/auth/v1/${path}`,{...init,headers:{apikey:config.anonKey,"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{}),...(init.headers||{})}})}async function parseError(response:Response){try{const body=await response.json();return body.msg||body.message||body.error_description||body.error||`Request failed (${response.status})`}catch{return `Request failed (${response.status})`}}
export async function consumeAuthHash(){if(typeof window==="undefined"||!window.location.hash)return null;const params=new URLSearchParams(window.location.hash.slice(1));const access=params.get("access_token");const refresh=params.get("refresh_token");if(!access||!refresh)return null;const session:AuthSession={access_token:access,refresh_token:refresh,expires_in:Number(params.get("expires_in")||3600),token_type:params.get("token_type")||"bearer"};saveSession(session);history.replaceState(null,"",window.location.pathname+window.location.search);return session}
export async function refreshSession(session:AuthSession){const response=await authFetch("token?grant_type=refresh_token",{method:"POST",body:JSON.stringify({refresh_token:session.refresh_token})});if(!response.ok){clearSession();throw new Error(await parseError(response))}const fresh=await response.json() as AuthSession;saveSession(fresh);return fresh}
export async function ensureSession(){await consumeAuthHash();let session=getStoredSession();if(!session)return null;const now=Math.floor(Date.now()/1000);if(session.expires_at&&session.expires_at-now<60){try{session=await refreshSession(session)}catch{return null}}return session}
export async function signIn(email:string,password:string){const response=await authFetch("token?grant_type=password",{method:"POST",body:JSON.stringify({email,password})});if(!response.ok)throw new Error(await parseError(response));const session=await response.json() as AuthSession;saveSession(session);return session}
export async function signUp(email:string,password:string){const redirect=typeof window!=="undefined"?`${window.location.origin}/account`:"";const response=await authFetch(`signup?redirect_to=${encodeURIComponent(redirect)}`,{method:"POST",body:JSON.stringify({email,password})});if(!response.ok)throw new Error(await parseError(response));const result=await response.json() as AuthSession&{identities?:unknown[]};if(result.access_token)saveSession(result);return result}
export async function requestPasswordReset(email:string){const redirect=typeof window!=="undefined"?`${window.location.origin}/reset-password`:"";const response=await authFetch(`recover?redirect_to=${encodeURIComponent(redirect)}`,{method:"POST",body:JSON.stringify({email})});if(!response.ok)throw new Error(await parseError(response))}
export async function updatePassword(password:string){const session=await ensureSession();if(!session)throw new Error("Your reset session has expired. Request another password reset.");const response=await authFetch("user",{method:"PUT",body:JSON.stringify({password})},session.access_token);if(!response.ok)throw new Error(await parseError(response))}
export async function currentUser(){const session=await ensureSession();if(!session)return null;const response=await authFetch("user",{method:"GET"},session.access_token);if(!response.ok){if(response.status===401)clearSession();return null}return await response.json() as AuthUser}
export async function signOut(){const session=getStoredSession();if(session){try{await authFetch("logout",{method:"POST"},session.access_token)}catch{}}clearSession()}
async function restFetch(path:string,init:RequestInit={}){const config=requireConfig();const session=await ensureSession();if(!session)throw new Error("Please sign in first.");const response=await fetch(`${config.baseUrl}/rest/v1/${path}`,{...init,headers:{apikey:config.anonKey,Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json",...(init.headers||{})}});if(!response.ok)throw new Error(await parseError(response));if(response.status===204)return null;const text=await response.text();return text?JSON.parse(text):null}
export async function listSavedRigs(){return await restFetch("saved_rigs?select=id,name,product_ids,created_at,updated_at&order=updated_at.desc") as SavedRig[]}export async function createSavedRig(userId:string,name:string,productIds:number[]){const result=await restFetch("saved_rigs",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({user_id:userId,name:name.trim()||"My Rig",product_ids:productIds})}) as SavedRig[];return result?.[0]}export async function deleteSavedRig(id:string){await restFetch(`saved_rigs?id=eq.${encodeURIComponent(id)}`,{method:"DELETE"})}export async function getProfile(userId:string){const rows=await restFetch(`profiles?select=id,plan,created_at,updated_at&id=eq.${encodeURIComponent(userId)}&limit=1`) as Profile[];return rows?.[0]||null}