-- SignalChainDB production schema starter (Supabase/Postgres)
create table if not exists brands(id bigint generated always as identity primary key,name text unique not null,slug text unique not null,website_url text);
create table if not exists categories(id bigint generated always as identity primary key,name text unique not null,slug text unique not null);
create table if not exists products(id bigint generated always as identity primary key,brand_id bigint references brands(id),category_id bigint references categories(id),name text not null,slug text unique not null,product_status text default 'active',verification_status text default 'catalog_only',description text,manufacturer_url text,msrp_usd numeric,verified_at date);
create table if not exists power_requirements(product_id bigint primary key references products(id) on delete cascade,voltage_v numeric,current_ma integer,polarity text,connector text,official_adapter text,notes text);
create table if not exists dimensions(product_id bigint primary key references products(id) on delete cascade,width_mm numeric,depth_mm numeric,height_mm numeric,weight_g numeric,notes text);
create table if not exists compatibility(id bigint generated always as identity primary key,source_product_id bigint references products(id) on delete cascade,target_product_id bigint references products(id) on delete cascade,compatibility_type text not null,status text not null,confidence text not null,requirements text,notes text,source_url text,verified_at date,unique(source_product_id,target_product_id,compatibility_type));
create table if not exists sources(id bigint generated always as identity primary key,product_id bigint references products(id) on delete cascade,source_type text not null,title text,publisher text,url text not null,accessed_at date not null,notes text);
-- Public reference data can be readable anonymously. User-owned tables should get stricter RLS later.
alter table brands enable row level security; alter table categories enable row level security; alter table products enable row level security; alter table power_requirements enable row level security; alter table dimensions enable row level security; alter table compatibility enable row level security; alter table sources enable row level security;
create policy "public read brands" on brands for select using (true); create policy "public read categories" on categories for select using (true); create policy "public read products" on products for select using (true); create policy "public read power" on power_requirements for select using (true); create policy "public read dimensions" on dimensions for select using (true); create policy "public read compatibility" on compatibility for select using (true); create policy "public read sources" on sources for select using (true);